# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('postal_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=255)),
                ('flat_number', models.CharField(max_length=255)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.City')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Reserved'), (1, 'Available')], default=1)),
                ('reservation_start_date', models.DateField()),
                ('reservation_end_date', models.DateField()),
                ('reserved_by', models.CharField(max_length=255)),
                ('flat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.Flat')),
            ],
        ),
    ]
