# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-26 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20170225_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_by',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
