# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-26 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_reserved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.Flat'),
        ),
    ]
